### ISSUE TITLE
Clients are creating TXs with 0 confirmations

### ISSUE THREAD

**Issue by wagerrdeveloper** [wagerr/WagerrCom#32]
Outcome
Transactions are being built using 0 confirm inputs. 

Expected Outcome
Use inputs that have at least 1 confirm.

https://github.com/wagerr/WagerrCom/blob/main/src/app/service/wgr-sports-book.service.ts#L213-L228

**Comment by WgrWebDev** [comment]
This has been solved at a internal Explorer Data Level
