### ISSUE TITLE
If spread value = 0 show 0

### ISSUE THREAD

**Issue by wagerrdeveloper** [wagerr/WagerrCom#33]
Currently shows + or - if Spread Value=0 and has price show Spread of 0 not +0 or -0

![image](https://user-images.githubusercontent.com/47796377/104036488-15a65300-5199-11eb-8761-f4240640a5d1.png)

**Comment by WgrWebDev** [comment]
https://github.com/wagerr/WagerrCom/pull/37/commits/1bd3efcc5967e61538ed14715cdae7287e47437a
