### ISSUE TITLE
Payout  Pending Mouse Over needs to be changed to 60 confirmations

### ISSUE THREAD

**Issue by wagerrdeveloper** [wagerr/WagerrCom#46]
Currently says 100 confirmations. This is changed in 4.0
Please have it say 60 confirmations and ensure looking for spendable inputs with 60 and not 100.

**Comment by WgrWebDev** [comment]
This is completed on the SportsBook Explorer Middleware

**Comment by wagerrdeveloper** [comment]
Is not complete on front end
