### ISSUE TITLE
Fix Weekly payment estimate to nodes on https://wagerr.com/about

### ISSUE THREAD

**Issue by zeroedge83** [wagerr/WagerrCom#83]
Please pull live data from https://explorer.wagerr.com/api/coin/ 

"oracleProfitPerSecond":0.1203275082026365 (this is for all nodes per second) 

covert this to oracle profit per week by multiplying by 604,800 then dividing by the number of nodes

**Comment by WgrWebDev** [comment]
This has been resolved in the backend
